name: Selenium Web Scraper - macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Set up ChromeDriver (download from provided link or use local path)
    - name: Download ChromeDriver
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/mac-arm64/chromedriver-mac-arm64.zip
        unzip chromedriver-mac-arm64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    # Run the Python script
    - name: Run Selenium script
      run: |
        source .venv/bin/activate
        python scraper.py

    # Post-job cleanup
    - name: Clean up
      if: always()
      run: |
        sudo rm -rf chromedriver
